export interface Patient{
    status: string;

}
export const data: Patient[] = [
    {
        status: "Active",
        patientId: 1,
        chart: 1,
        patientName: "john", 
        dob: "",
        gender: "",
        ssn: "",
        address: "",
        phone: "",
        action: ""
    },
    {
        status: "None",
        patientId: 2,
        chart: 2,
        patientName: "white", 
        dob: "",
        gender: "",
        ssn: "",
        address: "",
        phone: "",
        action: ""
    },
    {
        status: "Active",
        patientId: 3,
        chart: 3,
        patientName: "marry", 
        dob: "",
        gender: "",
        ssn: "",
        address: "",
        phone: "",
        action: ""
    },
    {
        status: "",
        patientId: 1,
        chart: 1,
        patientName: "john", 
        dob: "",
        gender: "",
        ssn: "",
        address: "",
        phone: "",
        action: ""
    },
    {
        status: "",
        patientId: 2,
        chart: 1,
        patientName: "white", 
        dob: "",
        gender: "",
        ssn: "",
        address: "",
        phone: "",
        action: ""
    },
    {
        status: "",
        patientId: 3,
        chart: 1,
        patientName: "marry", 
        dob: "",
        gender: "",
        ssn: "",
        address: "",
        phone: "",
        action: ""
    },
    {
        status: "",
        patientId: 1,
        chart: 1,
        patientName: "john", 
        dob: "",
        gender: "",
        ssn: "",
        address: "",
        phone: "",
        action: ""
    },
    {
        status: "",
        patientId: 2,
        chart: 1,
        patientName: "white", 
        dob: "",
        gender: "",
        ssn: "",
        address: "",
        phone: "",
        action: ""
    },
    {
        status: "",
        patientId: 3,
        chart: 1,
        patientName: "marry", 
        dob: "",
        gender: "",
        ssn: "",
        address: "",
        phone: "",
        action: ""
    },
    {
        status: "",
        patientId: 1,
        chart: 1,
        patientName: "john", 
        dob: "",
        gender: "",
        ssn: "",
        address: "",
        phone: "",
        action: ""
    },
    {
        status: "",
        patientId: 2,
        chart: 1,
        patientName: "white", 
        dob: "",
        gender: "",
        ssn: "",
        address: "",
        phone: "",
        action: ""
    },
    {
        status: "",
        patientId: 3,
        chart: 1,
        patientName: "marry", 
        dob: "",
        gender: "",
        ssn: "",
        address: "",
        phone: "",
        action: ""
    },
    {
        status: "",
        patientId: 1,
        chart: 1,
        patientName: "john", 
        dob: "",
        gender: "",
        ssn: "",
        address: "",
        phone: "",
        action: ""
    },
    {
        status: "",
        patientId: 2,
        chart: 1,
        patientName: "white", 
        dob: "",
        gender: "",
        ssn: "",
        address: "",
        phone: "",
        action: ""
    },
    {
        status: "",
        patientId: 3,
        chart: 1,
        patientName: "marry", 
        dob: "",
        gender: "",
        ssn: "",
        address: "",
        phone: "",
        action: ""
    },
    {
        status: "",
        patientId: 1,
        chart: 1,
        patientName: "john", 
        dob: "",
        gender: "",
        ssn: "",
        address: "",
        phone: "",
        action: ""
    },
    {
        status: "",
        patientId: 2,
        chart: 1,
        patientName: "white", 
        dob: "",
        gender: "",
        ssn: "",
        address: "",
        phone: "",
        action: ""
    },
    {
        status: "",
        patientId: 3,
        chart: 1,
        patientName: "marry", 
        dob: "",
        gender: "",
        ssn: "",
        address: "",
        phone: "",
        action: ""
    }
];